# Generated by Django 4.1.4 on 2023-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='shopapp.product'),
        ),
    ]
