# Generated by Django 4.1.4 on 2023-02-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_profile_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_image',
            field=models.ImageField(default='lion-fish.jpg', upload_to='static/images'),
        ),
    ]
